mkdir "Section 3 - Introduction to HTML"
mkdir "Section 4 - Intermediate HTML"
mkdir "Section 5 - Introduction to CSS"
mkdir "Section 6 - Intermediate CSS"
mkdir "Section 7 - Bootstrap (3)"
mkdir "Section 8 - Bootstrap 4!"
mkdir "Section 9 - Bootstrap 4 - Flexbox and Layout"
mkdir "Section 10 - Introduction to JavaScript"
mkdir "Section 11 - Javascript Basics - Control Flow"
mkdir "Section 12 - Javascript Basics - Functions"
mkdir "Section 13 - Javascript Basics - Arrays"
mkdir "Section 14 - Javascript Basics - Objects"
mkdir "Section 15 - DOM Manipulation"
mkdir "Section 16 - Advanced DOM Manipulation"
mkdir "Section 17 - Color Game Project"
mkdir "Section 18 - Intro to jQuery"
mkdir "Section 19 - Advanced jQuery"
mkdir "Section 20 - Todo List Projects"
mkdir "Section 21 - OPTIONAL Project - Patatap Clone"
mkdir "Section 22 - Backend Basics"
mkdir "Section 23 - The Command Line"
mkdir "Section 24 - Node JS"
mkdir "Section 25 - Server Side Frameworks"
mkdir "Section 26 - Intermediate Express"
mkdir "Section 27 - Working With API's"
mkdir "Section 28 - YelpCamp - Basics"
mkdir "Section 29 - Databases"
mkdir "Section 30 - YelpCamp - Data Persistence"
mkdir "Section 31 - RESTful Routing"
mkdir "Section 32 - Data Associations"
mkdir "Section 33 - YelpCamp - Comments"
mkdir "Section 34 - Authentication"
mkdir "Section 35 - YelpCamp - Adding Authentication"
mkdir "Section 36 - YelpCamp - Cleaning Up"
mkdir "Section 37 - YelpCamp - Update and Destroy"
mkdir "Section 38 - YelpCamp - UI Improvements"
mkdir "Section 39 - Git and Github"
mkdir "Section 40 - Deploying"
mkdir "Section 41 - JavaScript - The Tricky Stuff"
pause